def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
] 

pipeline {
    agent any
    
    environment {
        cluster = 'vprofile-production-cluster'
        service = 'vprofile-production-service'
    }

    stages {
        stage('Deploy to AWS ECS Production server'){
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'awscreds') {
                        sh "aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
                    }
                }
            }
        }
    post {
        always {
            echo 'Slack Notification'
            slackSend channel: '#jenkins-cicd',
                      color: COLOR_MAP[currentBuild.currentResult],
                      message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More Info at: ${env.BUILD_URL}"
        }
    }
}
}
